# Generated by Django 2.2.13 on 2020-09-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='pic',
            new_name='img',
        ),
    ]
